name: S3PO-GS
channels:
  - pytorch
  - nvidia
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.24.4
  - scipy
  - matplotlib
  - pandas
  - networkx
  - sympy
  - pillow
  - tqdm
  - pyyaml
  - opencv=4.8.1 
  - opencv
  - ffmpeg
  - pycolmap
  - cvxpy
  - tbb
  - glib
  - gmpy2
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - pytorch-cuda=11.8
  - cuda-nvcc=11.8.89

  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - configargparse==1.7
      - einops==0.8.0
      - evo==1.11.0
      - ffmpy==0.3.2
      - freetype-py==2.4.0
      - glfw==2.7.0
      - gradio==4.39.0
      - gradio-client==1.1.1
      - huggingface-hub==0.24.2
      - imageio==2.34.2
      - imgviz==1.7.5
      - kapture==1.1.10
      - kapture-localization==1.1.10
      - lpips==0.1.4
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.7
      - munch==4.0.0
      - numpy-quaternion==2023.0.4
      - open3d==0.18.0
      - piexif==1.1.3
      - pillow-heif==0.18.0
      - plotly==5.23.0
      - plyfile==1.0.3
      - poselib==2.0.2
      - pyglm==2.7.1
      - pyglet==1.5.29
      - pyopengl==3.1.0
      - pyquaternion==0.9.9
      - pyrender==0.1.45
      - python-dotenv==1.0.1
      - roma==1.5.0
      - scikit-learn==1.5.1
      - seaborn==0.13.2
      - tensorboard==2.17.0
      - tenacity==8.5.0
      - torchmetrics==1.4.0.post0
      - trimesh==4.4.3
      - typer==0.12.3
      - wandb==0.17.5
