inherit_from: "configs/mono/KITTI/base_config.yaml"

Dataset:
  dataset_path:  "/home/zwk/dataset/SemanticKITTI/SemanticKITTI/dataset/sequences/02/"
  begin: 0
  end: 200
  Calibration:
    fx: 718.856
    fy: 718.856
    cx: 607.1928
    cy: 185.2157
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 1241
    height: 376
    depth_scale: 200.0
    distorted: False

opt_params:
    position_lr_init: 0.0016
    position_lr_final: 0.00016
    init_lr: 6

Training:
    #alpha: 0.98
    mapping_itr_nosingle: 10
